channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.2
- pip:
  - mlflow==3.2.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==25.0
  - pandas==2.3.2
  - pyarrow==19.0.0
  - pyyaml==6.0.3
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
