{
 "title": "Prediction Drift Main",
 "time": { "from": "2022-01-27T08:10:31.453Z", "to": "2022-03-01T08:51:21.357Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT prediction_drift AS \"value\", \"timestamp\" AS \"time\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT share_missing_values AS \"value\", \"timestamp\" AS \"time\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT num_drifted_columns AS \"value\", \"timestamp\" AS \"time\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}